[#ftl]
[@addResourceGroupInformation
    type=TOPIC_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_SIMPLE_NOTIFICATION_SERVICE
        ]
/]

[@addResourceGroupInformation
    type=TOPIC_SUBSCRIPTION_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_SIMPLE_NOTIFICATION_SERVICE
        ]
/]
