[#ftl]

[@addComponent
    type=DATASTREAM_COMPONENT_TYPE
    properties=
        [
            {
                "Type" : "Description",
                "Value" : "A consumable stream of data generated by a system for a collection of clients to consume"
            },
            {
                "Type" : "Providers",
                "Value" : [ "aws" ]
            }
        ]
    attributes=
        [
            {
                "Names" : "Encryption",
                "Description" : "Manage the encryption used when interacting with the stream",
                "Children" : [
                    {
                        "Names": "Enabled",
                        "Description": "Enable encryption at rest of data stored in the stream",
                        "Types": BOOLEAN_TYPE,
                        "Default": true
                    }
                ]
            },
            {
                "Names": "Lifecycle",
                "Description" : "Manage the lifecyle of data stored in the stream",
                "Children" : [
                    {
                        "Names": "Expiration",
                        "Description" : "Time time in days to keep records in the stream for - _operations uses the layer Operations value",
                        "Types" : [ NUMBER_TYPE, STRING_TYPE ],
                        "Default" : "_operations"
                    }
                ]
            }
        ]
/]

[@addComponentDeployment
    type=DATASTREAM_COMPONENT_TYPE
    defaultGroup="solution"
/]
