[#ftl]

[#assign BLUEPRINT_VIEW_TYPE        = "blueprint" ]
[#assign CONFIGURATION_VIEW_TYPE    = "configuration" ]
[#assign SCHEMA_VIEW_TYPE           = "schema" ]
[#assign SCHEMALIST_VIEW_TYPE       = "schemalist" ]
[#assign INFO_VIEW_TYPE             = "info" ]
[#assign INPUTINFO_VIEW_TYPE        = "inputinfo" ]
[#assign LOADER_VIEW_TYPE           = "loader" ]
[#assign RELEASEINFO_VIEW_TYPE      = "releaseinfo" ]
[#assign VALIDATE_VIEW_TYPE         = "validate" ]
[#assign UNITLIST_VIEW_TYPE         = "unitlist" ]
