[#ftl]
[#switch mode]
    [#case "definition"]
                                [#list ecs.Tasks?values as task]
                                    [#if task?is_hash && (task.Slices!component.Slices)?seq_contains(slice)]
                                        [#if count > 0],[/#if]
                                        [@createTask tier=tier component=component task=task /]
                                        [#assign containerListMode = "supplemental"]
                                        [#list task.Containers?values as container]
                                            [#if container?is_hash]
                                                [#include containerList]
                                            [/#if]
                                        [/#list]
                                        [#assign count += 1]
                                    [/#if]
                                [/#list]
    [#break]
    [#case "outputs"]
                                [#list ecs.Tasks?values as task]
                                    [#if task?is_hash && (task.Slices!component.Slices)?seq_contains(slice)]
                                        [#if count > 0],[/#if]
                                            "ecsTaskX${tier.Id}X${component.Id}X${task.Id}" : {
                                                "Value" : { "Ref" : "ecsTaskX${tier.Id}X${component.Id}X${task.Id}" }
                                            }
                                            [#assign count += 1]
                                    [/#if]
                                [/#list]
    [#break]
[/#switch]