[#ftl]
[@addResourceGroupInformation
    type=DB_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_IDENTITY_SERVICE,
            AWS_CLOUDWATCH_SERVICE,
            AWS_KEY_MANAGEMENT_SERVICE,
            AWS_RELATIONAL_DATABASE_SERVICE,
            AWS_VIRTUAL_PRIVATE_CLOUD_SERVICE,
            AWS_AUTOSCALING_SERVICE
        ]
/]
