[#ftl]
[@addResourceGroupInformation
    type=APIGATEWAY_USAGEPLAN_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_APIGATEWAY_SERVICE
        ]
/]