[#ftl]
[#assign count = 0]
[#list tiers as tier]
    [#if tier.Components??]
        [#list tier.Components?values as component]
            [#if component?is_hash && component.Slices?seq_contains(slice)]
                [#if count > 0],[/#if]
                [#if component.MultiAZ??]
                    [#assign multiAZ =  component.MultiAZ]
                [#else]
                    [#assign multiAZ =  solnMultiAZ]
                [/#if]
                [#include "/"+solutionList]
            [/#if]
        [/#list]
    [/#if]
[/#list]
