[#ftl]

[#-- Resources --]
[#-- At the moment, the condition resource types are being     --]
[#-- generated by prepending "waf" to the condition type       --]
[#-- If they end up needing custom attributes, then individual --]
[#-- reousrce type definitions will be needed here but for now --]
[#-- AWs hasn't defined any of interest                        --]
[#assign AWS_WAF_RULE_RESOURCE_TYPE = "wafRule" ]
[#assign AWS_WAF_ACL_RESOURCE_TYPE = "wafAcl" ]
[#assign AWS_WAF_ACL_ASSOCIATION_RESOURCE_TYPE = "wafAssoc" ]

[#-- TODO(mfl): Deprecate direct creation of IPSet rule --]
[#assign AWS_WAF_IPSET_RESOURCE_TYPE = "wafIpSet" ]
[#function formatWAFIPSetId group regional=false ]
    [#return regional?then(
            formatAccountResourceId(
                AWS_WAF_IPSET_RESOURCE_TYPE,
                group),
            formatAccountResourceId(
                AWS_WAF_IPSET_RESOURCE_TYPE,
                group))
    ]
[/#function]
[#function formatWAFIPSetRuleId group]
    [#return formatDependentWAFRuleId(
                formatWAFIPSetId(group))]
[/#function]

[#function formatWAFConditionId type ids...]
    [#return formatResourceId(
                "waf" + type,
                ids)]
[/#function]

[#function formatDependentWAFConditionId type resourceId extensions...]
    [#return formatDependentResourceId(
                "waf" + type,
                resourceId,
                extensions)]
[/#function]

[#function formatWAFRuleId ids...]
    [#return formatResourceId(
                AWS_WAF_RULE_RESOURCE_TYPE,
                ids)]
[/#function]

[#function formatDependentWAFRuleId resourceId extensions...]
    [#return formatDependentResourceId(
                AWS_WAF_RULE_RESOURCE_TYPE,
                resourceId,
                extensions)]
[/#function]

[#function formatWAFAclId ids...]
    [#return formatResourceId(
                AWS_WAF_ACL_RESOURCE_TYPE,
                ids)]
[/#function]

[#function formatDependentWAFAclId resourceId extensions...]
    [#return formatDependentResourceId(
                AWS_WAF_ACL_RESOURCE_TYPE,
                resourceId,
                extensions)]
[/#function]

[#function formatWAFAclAssociationId ids...]
    [#return formatResourceId(
                AWS_WAF_ACL_ASSOCIATION_RESOURCE_TYPE,
                ids)]
[/#function]

[#function formatDependentWAFAclAssociationId resourceId extensions...]
    [#return formatDependentResourceId(
                AWS_WAF_ACL_ASSOCIATION_RESOURCE_TYPE,
                resourceId,
                extensions)]
[/#function]

