[#ftl]

[#-- Core Tasks --]
[#assign CREATE_SCHEMA_TASK_TYPE            = "create_schema" ]
[#assign PROCESS_TEMPLATE_PASS_TASK_TYPE    = "process_template_pass" ]
[#assign MANAGE_DEPLOYMENT_TASK_TYPE        = "manage_deployment" ]
[#assign INSTALL_PLUGIN_TASK_TYPE           = "install_plugin" ]
[#assign RENAME_FILE_TASK_TYPE              = "rename_file" ]
[#assign RUN_BASH_SCRIPT_TASK_TYPE          = "run_bash_script" ]
[#assign BASH_RUN_COMMAND_TASK_TYPE         = "bash_run_command" ]
[#assign CONDITIONAL_STAGE_SKIP_TASK_TYPE   = "conditional_stage_skip" ]
[#assign SSH_RUN_COMMAND_TASK_TYPE          = "ssh_run_command" ]
[#assign SSH_COPY_FILE_TASK_TYPE            = "ssh_copy_file" ]
[#assign SET_PROVIDER_CREDENTIALS_TASK_TYPE = "set_provider_credentials" ]
