[#ftl]
[@addResourceGroupInformation
    type=CONFIGSTORE_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_DYNAMODB_SERVICE
        ]
/]

[@addResourceGroupInformation
    type=CONFIGSTORE_BRANCH_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_DYNAMODB_SERVICE
        ]
/]