[#ftl]
[@addResourceGroupInformation
    type=S3_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_SIMPLE_STORAGE_SERVICE
        ]
/]
