[#ftl]
[@addResourceGroupInformation
    type=S3_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_SIMPLE_STORAGE_SERVICE,
            AWS_SIMPLE_QUEUEING_SERVICE,
            AWS_SIMPLE_NOTIFICATION_SERVICE,
            AWS_LAMBDA_SERVICE,
            AWS_IDENTITY_SERVICE
        ]
/]
