[#ftl]
[#assign resourceCount = 0]
[#list tiers as tier]
    [#if tier.Components??]
        [#list tier.Components?values as component]
            [#if deploymentRequired(component, deploymentUnit)]
                [#assign componentId = component.Id]
                [#assign componentType = ""]
                [#if component.Id?contains("-")]
                    [#assign componentId = component.Id?split("-")[0]]
                    [#assign componentType = component.Id?split("-")[1]?lower_case]
                [#/if]
                [#assign componentIdStem = formatId(tier.Id, componentId)]
                [#assign componentNameStem = formatName(productName, segmentName, tier.Name, component.Name)]
                [#assign multiAZ = solnMultiAZ]
                [#list component as key, value]
                    [#switch key]
                        [#case "Id"]
                        [#case "Name"]
                        [#case "Title"]
                        [#case "Description"]
                        [#case "DeploymentUnits"]
                            [break]

                        [#case "MultiAZ"]
                            [#assign multiAZ = value]
                            [#break]

                        [#default]
                            [#if componentType == ""]
                                [#assign componentType = key?lower_case]
                            [/#if]
                            [#break]
                    [/#switch]
                [/#list]
                [#assign typedComponentIdStem = formatId(componentType, componentIdStem]
                [#include compositeList]
            [/#if]
        [/#list]
    [/#if]
[/#list]
