[#ftl]
[@addResourceGroupInformation
    type=SQS_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_SIMPLE_QUEUEING_SERVICE
        ]
/]
