[#ftl]
[@addResourceGroupInformation
    type=RDS_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_CLOUDWATCH_SERVICE,
            AWS_KEY_MANAGEMENT_SERVICE,
            AWS_RELATIONAL_DATABASE_SERVICE,
            AWS_VIRTUAL_PRIVATE_CLOUD_SERVICE
        ]
/]
