[#ftl]
[@addResourceGroupInformation
    type=OBJECTSQL_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_ATHENA_SERVICE
        ]
/]
