[#ftl]

[#-- Services --]
[#assign AWS_APIGATEWAY_SERVICE = "apigateway"]
[#assign AWS_ATHENA_SERVICE = "athena"]
[#assign AWS_CERTIFICATE_MANAGER_SERVICE = "acm"]
[#assign AWS_CLOUDFRONT_SERVICE = "cf"]
[#assign AWS_CLOUDMAP_SERVICE = "cloudmap"]
[#assign AWS_CLOUDWATCH_SERVICE = "cw"]
[#assign AWS_COGNITO_SERVICE = "cognito"]
[#assign AWS_DATA_PIPELINE_SERVICE = "datapipeline"]
[#assign AWS_DYNAMODB_SERVICE = "dynamodb"]
[#assign AWS_ELASTICACHE_SERVICE = "cache"]
[#assign AWS_ELASTICSEARCH_SERVICE = "es"]
[#assign AWS_ELASTIC_COMPUTE_SERVICE = "ec2"]
[#assign AWS_ELASTIC_CONTAINER_SERVICE = "ecs"]
[#assign AWS_ELASTIC_FILE_SYSTEM_SERVICE = "efs"]
[#assign AWS_ELASTIC_LOAD_BALANCER_SERVICE = "lb"]
[#assign AWS_IDENTITY_SERVICE = "iam"]
[#assign AWS_KEY_MANAGEMENT_SERVICE = "kms"]
[#assign AWS_KINESIS_SERVICE = "kinesis"]
[#assign AWS_LAMBDA_SERVICE = "lambda"]
[#assign AWS_RELATIONAL_DATABASE_SERVICE = "rds"]
[#assign AWS_ROUTE53_SERVICE = "dns"]
[#assign AWS_SIMPLE_STORAGE_SERVICE = "s3"]
[#assign AWS_SIMPLE_EMAIL_SERVICE = "ses"]
[#assign AWS_SIMPLE_NOTIFICATION_SERVICE = "sns"]
[#assign AWS_SIMPLE_QUEUEING_SERVICE = "sqs"]
[#assign AWS_SYSTEMS_MANAGER_SERVICE = "ssm"]
[#assign AWS_VIRTUAL_PRIVATE_CLOUD_SERVICE = "vpc"]
[#assign AWS_WEB_APPLICATION_FIREWALL_SERVICE = "waf"]
[#assign AWS_AUTOSCALING_SERVICE="autoscaling"]

[#-- Pseudo services --]
[#assign AWS_BASELINE_PSEUDO_SERVICE = "baseline"]
