[#ftl]

[#-- Shared Entrances --]
[#assign DEPLOYMENT_ENTRANCE_TYPE        = "deployment" ]
[#assign DEPLOYMENTTEST_ENTRANCE_TYPE    = "deploymenttest" ]
[#assign BLUEPRINT_ENTRANCE_TYPE         = "blueprint" ]
[#assign BUILDBLUEPRINT_ENTRANCE_TYPE    = "buildblueprint" ]
[#assign UNITLIST_ENTRANCE_TYPE          = "unitlist" ]
[#assign SCHEMA_ENTRANCE_TYPE            = "schema" ]
[#assign SCHEMASET_ENTRANCE_TYPE         = "schemaset" ]
[#assign INFO_ENTRANCE_TYPE              = "info" ]
[#assign VALIDATE_ENTRANCE_TYPE          = "validate" ]
[#assign OCCURRENCES_ENTRANCE_TYPE       = "occurrences" ]
