[#ftl]

[#-- Shared Entrances --]
[#assign BLUEPRINT_ENTRANCE_TYPE         = "blueprint" ]
[#assign BUILDBLUEPRINT_ENTRANCE_TYPE    = "buildblueprint" ]
[#assign CONFIGURATION_ENTRANCE_TYPE     = "configuration" ]
[#assign DEPLOYMENT_ENTRANCE_TYPE        = "deployment" ]
[#assign DEPLOYMENTTEST_ENTRANCE_TYPE    = "deploymenttest" ]
[#assign INFO_ENTRANCE_TYPE              = "info" ]
[#assign LOADER_ENTRANCE_TYPE            = "loader" ]
[#assign SCHEMA_ENTRANCE_TYPE            = "schema" ]
[#assign SCHEMALIST_ENTRANCE_TYPE        = "schemalist" ]
[#assign OCCURRENCES_ENTRANCE_TYPE       = "occurrences" ]
[#assign RELEASEINFO_ENTRANCE_TYPE       = "releaseinfo" ]
[#assign UNITLIST_ENTRANCE_TYPE          = "unitlist" ]
[#assign VALIDATE_ENTRANCE_TYPE          = "validate" ]
