name: package

on:

  # Workflow run will run after another job has completed
  # so we wait for the workflow to complete then get going
  workflow_run:
    workflows:
      - 'testing'

    branches:
      - 'master'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: add build details
        run: |
          pip install hamlet-cli
          hamlet engine add-engine-source-build

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{github.repository}}
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}
          tags: |
            type=semver,pattern={{version}}

      - name: build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/*') || github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: base_package
