name: package

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          tags: "ghcr.io/${{ github.repository}}:latest"
          push: true
          target: base_package

      - name: Get the tag name
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Push Release
        if: startsWith(github.ref, 'refs/tags/' )
        uses: docker/build-push-action@v2
        with:
          tags: "ghcr.io/${{github.repository}}:${{ steps.get_tag_name.outputs.TAG_NAME }}"
          push: true
          target: base_package
