name: testing

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  deploy_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install
        run: |
          pip install --pre hamlet-cli

          sudo apt-get update
          sudo apt-get install -y jq dos2unix

      - name: Run Tests
        env:
          GENERATION_PLUGIN_DIRS: ${{ github.workspace }}
          TEST_OUTPUT_DIR: ${{ github.workspace }}/hamlet_tests
        run: |
          hamlet engine set-engine unicycle
          hamlet -i mock -p shared -p sharedtest -f default deploy test-deployments -p '--junitxml=junit.xml' -o "${TEST_OUTPUT_DIR}"
