name: testing

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  deploy_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install
        run: |
          pip install hamlet-cli
          sudo apt-get install -y jq dos2unix

      - name: Run Tests
        env:
          GENERATION_ENGINE_DIR: ${{github.workspace }}
          GENERATION_PLUGIN_DIRS: ${{ github.workspace }}
        run: |
          hamlet engine set-engine unicycle
          hamlet -i mock -p shared -p sharedtest -f default deploy test-deployments -p '--junitxml=junit.xml' -o 'hamlet_tests/'

      - name: Test Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'hamlet_tests/junit.xml'
          fail_on_failure: true
          require_tests: true
          check_name: deploy_tests results
